package com.abbiya.broadr.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig boardDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig locationDaoConfig;
    private final DaoConfig registrationMessageDaoConfig;

    private final BoardDao boardDao;
    private final MessageDao messageDao;
    private final CommentDao commentDao;
    private final LocationDao locationDao;
    private final RegistrationMessageDao registrationMessageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        boardDaoConfig = daoConfigMap.get(BoardDao.class).clone();
        boardDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        registrationMessageDaoConfig = daoConfigMap.get(RegistrationMessageDao.class).clone();
        registrationMessageDaoConfig.initIdentityScope(type);

        boardDao = new BoardDao(boardDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);
        registrationMessageDao = new RegistrationMessageDao(registrationMessageDaoConfig, this);

        registerDao(Board.class, boardDao);
        registerDao(Message.class, messageDao);
        registerDao(Comment.class, commentDao);
        registerDao(Location.class, locationDao);
        registerDao(RegistrationMessage.class, registrationMessageDao);
    }

    public void clear() {
        boardDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        locationDaoConfig.getIdentityScope().clear();
        registrationMessageDaoConfig.getIdentityScope().clear();
    }

    public BoardDao getBoardDao() {
        return boardDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public RegistrationMessageDao getRegistrationMessageDao() {
        return registrationMessageDao;
    }

}
