package com.abbiya.broadr.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table LOCATION.
 */
public class Location {

    private Long id;
    private String uuid;
    private String latitude;
    private String longitude;

    public Location() {
    }

    public Location(Long id) {
        this.id = id;
    }

    public Location(Long id, String uuid, String latitude, String longitude) {
        this.id = id;
        this.uuid = uuid;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

}
